###local
POST http://localhost:3000/user
content-type: application/json
Authorization: Bearer 1234

{
    "email": "test2@gmail.com",
    "password": "asdfQWEasdf09"
}

###

POST https://assistant-tpm-backend.onrender.com/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjMzdkNTkzNjVjNjIyOGI4Y2NkYWNhNTM2MGFjMjRkMDQxNWMxZWEiLCJ0eXAiOiJKV1QifQ

{
    "email": "test@gmail.com",
    "password": "asdfQWEasdf09"
}