###local
POST http://localhost:8080/userAdmin
content-type: application/json
Authorization: Bearer 1234

{
    "email": "cesar@admin.com",
    "password": "asdfQWEasdf09"
}

###

POST http://localhost:8080/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjMzdkNTkzNjVjNjIyOGI4Y2NkYWNhNTM2MGFjMjRkMDQxNWMxZWEiLCJ0eXAiOiJKV1QifQ

{
    "email": "test@gmail.com",
    "password": "asdfQWEasdf09"
}