###
GET http://localhost:8080/hello-world


###
POST http://localhost:8080/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjMzdkNTkzNjVjNjIyOGI4Y2NkYWNhNTM2MGFjMjRkMDQxNWMxZWEiLCJ0eXAiOiJKV1QifQ

{
    "email": "test@gmail.com",
    "password": "asdfQWEasdf09"
}


###
GET http://localhost:8080/users

